In [2]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/eyowhite/Messy-dataset/main/warehouse_messy_data.csv"
df = pd.read_csv(url)

In [6]:
print(df.columns)
#Looking for invisible spaces

Index(['Product ID', 'Product Name', 'Category', 'Warehouse', 'Location',
       'Quantity', 'Price', 'Supplier', 'Status', 'Last Restocked'],
      dtype='str')

In [7]:
df.columns.str.strip()
#Checking if anything changed after looking for invisible spaces

Index(['Product ID', 'Product Name', 'Category', 'Warehouse', 'Location',
       'Quantity', 'Price', 'Supplier', 'Status', 'Last Restocked'],
      dtype='str')

In [5]:
df.isnull().sum()
#finding nan's and missing values

Product ID          0
Product Name        0
Category            0
Warehouse           0
Location            0
Quantity          158
Price             207
Supplier            0
Status              0
Last Restocked    200
dtype: int64

In [9]:
df.groupby('Category').apply(lambda x: x.isnull().sum())
#finding non-random missing data

,Product ID,Product Name,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
Category,,,,,,,,,
CLOTHING,0,0,0,0,56,58,0,0,53
ELECTRONICS,0,0,0,0,26,46,0,0,55
FURNITURE,0,0,0,0,39,48,0,0,44
TOYS,0,0,0,0,37,55,0,0,48

In [11]:
df.dtypes
#Checking for the right data types in each column

Product ID          int64
Product Name          str
Category              str
Warehouse             str
Location              str
Quantity              str
Price             float64
Supplier              str
Status                str
Last Restocked        str
dtype: object

In [17]:
df['Quantity'].unique()

<StringArray>
['300', 'two hundred', '100', '50', nan, '150']
Length: 6, dtype: str

In [14]:
df.duplicated().sum()
#looking for duplicate rows

np.int64(0)

In [3]:
df[df.duplicated()]

Empty DataFrame
Columns: [Product ID, Product Name, Category, Warehouse, Location, Quantity, Price, Supplier, Status, Last Restocked]
Index: []

In [22]:
df.duplicated(subset=['Product ID'])
#looking for duplicates in the subset "Product id"

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996     True
997     True
998     True
999    False
Length: 1000, dtype: bool

In [23]:
df.describe()
#looking for impossible values

        Product ID       Price
count  1000.000000  793.000000
mean   1503.929000   28.085839
std     289.998108   14.686312
min    1000.000000    9.990000
25%    1242.750000   19.990000
50%    1505.000000   29.990000
75%    1757.250000   49.990000
max    1998.000000   49.990000

In [4]:
df.sort_values(by='Price', ascending=False).head()
#Checking if pricing makes sense for items to eliminate outliers

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
3,1270,gadget z,TOYS,Warehouse 2,Aisle 4,50,49.99,Supplier B,In Stock,20/12/2022
10,1466,widget a,CLOTHING,Warehouse 3,Aisle 1,NaN,49.99,Supplier B,In Stock,15/01/2023
999,1250,widget a,CLOTHING,Warehouse 1,Aisle 3,100,49.99,Supplier B,Out of Stock,20/12/2022
998,1241,widget c,FURNITURE,Warehouse 2,Aisle 2,100,49.99,Supplier C,Low Stock,20/12/2022
965,1177,widget c,ELECTRONICS,Warehouse 3,Aisle 2,300,49.99,Supplier B,In Stock,15/01/2023

In [24]:
df.describe(include='all')

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
count,1000.000000,1000,1000,1000,1000,842,793.000000,1000,1000,800
unique,NaN,6,4,3,5,5,NaN,4,3,4
top,NaN,gadget y,FURNITURE,Warehouse 1,Aisle 3,300,NaN,Supplier B,In Stock,20/12/2022
freq,NaN,177,265,349,211,177,NaN,288,340,218
mean,1503.929000,NaN,NaN,NaN,NaN,NaN,28.085839,NaN,NaN,NaN
std,289.998108,NaN,NaN,NaN,NaN,NaN,14.686312,NaN,NaN,NaN
min,1000.000000,NaN,NaN,NaN,NaN,NaN,9.990000,NaN,NaN,NaN
25%,1242.750000,NaN,NaN,NaN,NaN,NaN,19.990000,NaN,NaN,NaN
50%,1505.000000,NaN,NaN,NaN,NaN,NaN,29.990000,NaN,NaN,NaN
75%,1757.250000,NaN,NaN,NaN,NaN,NaN,49.990000,NaN,NaN,NaN
max,1998.000000,NaN,NaN,NaN,NaN,NaN,49.990000,NaN,NaN,NaN

Fixing string errors in int coloumns and rows

In [27]:
df[df['Price'] < 100]
#Isolating rows

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1102,gadget y,ELECTRONICS,Warehouse 2,Aisle 1,300,9.99,Supplier C,In Stock,NaN
1,1435,gadget y,ELECTRONICS,Warehouse 2,Aisle 4,two hundred,19.99,Supplier C,Out of Stock,NaN
2,1860,widget a,CLOTHING,Warehouse 2,Aisle 3,100,19.99,Supplier B,In Stock,20/12/2022
3,1270,gadget z,TOYS,Warehouse 2,Aisle 4,50,49.99,Supplier B,In Stock,20/12/2022
4,1106,widget a,FURNITURE,Warehouse 3,Aisle 3,two hundred,9.99,Supplier D,Out of Stock,25/04/2023
...,...,...,...,...,...,...,...,...,...,...
994,1449,gadget x,FURNITURE,Warehouse 2,Aisle 3,NaN,29.99,Supplier B,Out of Stock,NaN
996,1823,gadget y,ELECTRONICS,Warehouse 2,Aisle 3,300,19.99,Supplier B,In Stock,20/12/2022
997,1797,gadget z,TOYS,Warehouse 3,Aisle 5,150,9.99,Supplier C,Low Stock,05/03/2023
998,1241,widget c,FURNITURE,Warehouse 2,Aisle 2,100,49.99,Supplier C,Low Stock,20/12/2022
999,1250,widget a,CLOTHING,Warehouse 1,Aisle 3,100,49.99,Supplier B,Out of Stock,20/12/2022

In [14]:
#converting spelling error 'widget' to 'gadget'
print(df['Product Name'].unique())
spelling_fixes = {
    'widget': 'gadget',
    'widget ' : 'gadget' }

df['Product Name'] = df['Product Name'].replace(spelling_fixes)

<StringArray>
[' gadget y ', ' widget a ', ' gadget z ', ' widget b ', ' widget c ',
 ' gadget x ']
Length: 6, dtype: str

In [15]:
df['Product Name'] = df['Product Name'].str.replace('widget', 'gadget', case=False)

In [16]:
print(df['Product Name'].unique())

<StringArray>
[' gadget y ', ' gadget a ', ' gadget z ', ' gadget b ', ' gadget c ',
 ' gadget x ']
Length: 6, dtype: str

##FIxin NaN values

In [17]:
#Fixing missing Data (NaN)
print(df.isnull().sum())

Product ID          0
Product Name        0
Category            0
Warehouse           0
Location            0
Quantity          318
Price             207
Supplier            0
Status              0
Last Restocked    200
dtype: int64

In [22]:
df.dropna(how='all', inplace=True)

In [32]:
mean = df['Price'].mean() #finding the mean
print(mean)

22.272070000000003

In [31]:
df.fillna({'Price': mean}, inplace=True) #replacing Nan values with the mean price

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1102,gadget y,ELECTRONICS,Warehouse 2,Aisle 1,300.0,9.99,Supplier C,In Stock,0
1,1435,gadget y,ELECTRONICS,Warehouse 2,Aisle 4,0.0,19.99,Supplier C,Out of Stock,0
2,1860,gadget a,CLOTHING,Warehouse 2,Aisle 3,100.0,19.99,Supplier B,In Stock,20/12/2022
3,1270,gadget z,TOYS,Warehouse 2,Aisle 4,50.0,49.99,Supplier B,In Stock,20/12/2022
4,1106,gadget a,FURNITURE,Warehouse 3,Aisle 3,0.0,9.99,Supplier D,Out of Stock,25/04/2023
...,...,...,...,...,...,...,...,...,...,...
995,1009,gadget b,FURNITURE,Warehouse 2,Aisle 2,100.0,0.00,Supplier C,In Stock,15/01/2023
996,1823,gadget y,ELECTRONICS,Warehouse 2,Aisle 3,300.0,19.99,Supplier B,In Stock,20/12/2022
997,1797,gadget z,TOYS,Warehouse 3,Aisle 5,150.0,9.99,Supplier C,Low Stock,05/03/2023
998,1241,gadget c,FURNITURE,Warehouse 2,Aisle 2,100.0,49.99,Supplier C,Low Stock,20/12/2022
999,1250,gadget a,CLOTHING,Warehouse 1,Aisle 3,100.0,49.99,Supplier B,Out of Stock,20/12/2022

In [33]:
df.fillna({'Last Restocked': '_'}, inplace=True)

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1102,gadget y,ELECTRONICS,Warehouse 2,Aisle 1,300.0,9.99,Supplier C,In Stock,0
1,1435,gadget y,ELECTRONICS,Warehouse 2,Aisle 4,0.0,19.99,Supplier C,Out of Stock,0
2,1860,gadget a,CLOTHING,Warehouse 2,Aisle 3,100.0,19.99,Supplier B,In Stock,20/12/2022
3,1270,gadget z,TOYS,Warehouse 2,Aisle 4,50.0,49.99,Supplier B,In Stock,20/12/2022
4,1106,gadget a,FURNITURE,Warehouse 3,Aisle 3,0.0,9.99,Supplier D,Out of Stock,25/04/2023
...,...,...,...,...,...,...,...,...,...,...
995,1009,gadget b,FURNITURE,Warehouse 2,Aisle 2,100.0,0.00,Supplier C,In Stock,15/01/2023
996,1823,gadget y,ELECTRONICS,Warehouse 2,Aisle 3,300.0,19.99,Supplier B,In Stock,20/12/2022
997,1797,gadget z,TOYS,Warehouse 3,Aisle 5,150.0,9.99,Supplier C,Low Stock,05/03/2023
998,1241,gadget c,FURNITURE,Warehouse 2,Aisle 2,100.0,49.99,Supplier C,Low Stock,20/12/2022
999,1250,gadget a,CLOTHING,Warehouse 1,Aisle 3,100.0,49.99,Supplier B,Out of Stock,20/12/2022

FIxing and removing duplicates

In [34]:
#Removing false Duplicates
print(df[df.duplicated(keep=False)])

Empty DataFrame
Columns: [Product ID, Product Name, Category, Warehouse, Location, Quantity, Price, Supplier, Status, Last Restocked]
Index: []

In [37]:
print(df.duplicated().sum()) #finding a total number of duplicate rows

0

In [38]:
print(df[df.duplicated(keep=False)])

Empty DataFrame
Columns: [Product ID, Product Name, Category, Warehouse, Location, Quantity, Price, Supplier, Status, Last Restocked]
Index: []

In [40]:
print(df.duplicated(subset=['Product ID', 'Warehouse']).sum())

166

In [41]:
df.drop_duplicates(inplace=True)

In [46]:
before = len(df)
print(f"Before: {len(df)} rows")
df.drop_duplicates(inplace=True)
#checking number of rows before removing duplicates

Before: 1000 rows

In [47]:
print(f"After: {len(df)} rows")
print(f"Removed: {before - len(df)} ghost entries")
#checking number of rows after removing duplicates

After: 1000 rows
Removed: 0 ghost entries

Fixing Outliers

In [48]:
print(df.describe())

        Product ID     Quantity        Price
count  1000.000000  1000.000000  1000.000000
mean   1503.929000   103.900000    22.272070
std     289.998108   105.431997    17.338108
min    1000.000000     0.000000     0.000000
25%    1242.750000     0.000000     9.990000
50%    1505.000000   100.000000    19.990000
75%    1757.250000   150.000000    29.990000
max    1998.000000   300.000000    49.990000

In [49]:
print(df[df['Quantity'] < 0])

Empty DataFrame
Columns: [Product ID, Product Name, Category, Warehouse, Location, Quantity, Price, Supplier, Status, Last Restocked]
Index: []

In [50]:
print(df[df['Price'] <= 0])

     Product ID Product Name   Category    Warehouse Location  Quantity  \
5          1071    gadget b    CLOTHING  Warehouse 3  Aisle 5     300.0
14         1087    gadget a        TOYS  Warehouse 3  Aisle 3      50.0
17         1871    gadget b    CLOTHING  Warehouse 2  Aisle 2     100.0
21         1308    gadget y    CLOTHING  Warehouse 1  Aisle 1     300.0
32         1459    gadget y    CLOTHING  Warehouse 3  Aisle 2     100.0
..          ...          ...        ...          ...      ...       ...
984        1557    gadget b        TOYS  Warehouse 3  Aisle 2     300.0
986        1252    gadget y    CLOTHING  Warehouse 3  Aisle 4       0.0
988        1593    gadget b    CLOTHING  Warehouse 1  Aisle 1     100.0
991        1708    gadget z        TOYS  Warehouse 3  Aisle 1       0.0
995        1009    gadget b   FURNITURE  Warehouse 2  Aisle 2     100.0

     Price    Supplier        Status Last Restocked
5      0.0  Supplier A      In Stock     20/12/2022
14     0.0  Supplier C  Out of Stock     15/01/2023
17     0.0  Supplier D  Out of Stock     25/04/2023
21     0.0  Supplier C  Out of Stock     25/04/2023
32     0.0  Supplier D  Out of Stock     20/12/2022
..     ...         ...           ...            ...
984    0.0  Supplier A  Out of Stock     05/03/2023
986    0.0  Supplier A      In Stock     05/03/2023
988    0.0  Supplier A  Out of Stock     25/04/2023
991    0.0  Supplier C     Low Stock     05/03/2023
995    0.0  Supplier C      In Stock     15/01/2023

[207 rows x 10 columns]

In [51]:
print(df[df['Price'] > 10000])
#shows no extreme values

Empty DataFrame
Columns: [Product ID, Product Name, Category, Warehouse, Location, Quantity, Price, Supplier, Status, Last Restocked]
Index: []

Checks after cleaning

In [52]:
print(df.shape)

(1000, 10)

In [53]:
print(df.isnull().sum()) # confirming no remaing NaN values

Product ID        0
Product Name      0
Category          0
Warehouse         0
Location          0
Quantity          0
Price             0
Supplier          0
Status            0
Last Restocked    0
dtype: int64

In [54]:
print(df.dtypes) #confirming correct data types

Product ID          int64
Product Name          str
Category              str
Warehouse             str
Location              str
Quantity          float64
Price             float64
Supplier              str
Status                str
Last Restocked     object
dtype: object

In [55]:
df.reset_index(drop=True, inplace=True)
# renumbering indexes after removing duplicates

In [60]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [30]:
#Fixing error with Quantity by converting column to be numeric
word_map = {'two hundred': 200}
df['Quantity'] = df['Quantity'].replace(word_map)
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [31]:
df.to_csv('warehouse_clean.csv', index=False)